spring:
  application:
    name: core-service
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: vitalpaw.devtester007@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
server:
  port: ${CORE_SERVICE_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health
api:
  key: ${API_KEY}
app:
  image:
    storage-path: /app/images/pets