version: "3.8"

networks:
  vitalpaw-network:
    external: true

services:
  core-service:
    image: 161.132.38.142:5000/coreservice:latest
    environment:
      - DB_HOST=db_mariadb
      - DB_PORT=3306
      - DB_NAME=vitalpawdb
      - DB_USERNAME=vitalpaw
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    secrets:
      - db_password
      - mail_password
      - api_key
    networks:
      - vitalpaw-network
    volumes:
      - vitalpaw_photos:/app/photos
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 1m30s
      resources:
        limits:
          cpus: '1.0'
          memory: 1.5G
        reservations:
          memory: 768M
          cpus: '0.5'
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.core-api.rule=Host(`vitalpaw.tecsup.xyz`) && PathPrefix(`/api`)"
        - "traefik.http.routers.core-api.entrypoints=websecure"
        - "traefik.http.routers.core-api.service=core-service"
        - "traefik.http.routers.core-api.tls=true"
        - "traefik.http.routers.core-api.tls.certresolver=letsencrypt"
        - "traefik.http.routers.swagger-ui.rule=Host(`vitalpaw.tecsup.xyz`) && (PathPrefix(`/swagger-ui`) || PathPrefix(`/v3/api-docs`))"
        - "traefik.http.routers.swagger-ui.entrypoints=websecure"
        - "traefik.http.routers.swagger-ui.service=core-service"
        - "traefik.http.routers.swagger-ui.tls=true"
        - "traefik.http.routers.swagger-ui.tls.certresolver=letsencrypt"
        - "traefik.http.services.core-service.loadbalancer.server.port=8080"
secrets:
  db_password:
    external: true
  mail_password:
    external: true
  api_key:
    external: true

volumes:
  vitalpaw_photos:
    driver: local