version: '3.8'

services:
  ollama-gpu:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama-gpu
    ports:
      - "11440:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      OLLAMA_KEEP_ALIVE: "10m"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 15s
      timeout: 10s
      retries: 6
      start_period: 10s

  qdrant:
    build:
      context: .
      dockerfile: Dockerfile.qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 15s
      timeout: 10s
      retries: 6
      start_period: 10s
    restart: unless-stopped

  backend-ollama-api:
    build: ./backend_ollama_python
    container_name: backend-ollama-api
    ports:
      - "8000:8000"
    environment:
      OLLAMA_GPU_HOST: http://ollama-gpu:11434
      QDRANT_HOST: http://qdrant:6333
      LLM_MODEL: phi4-mini:3.8b
      EMBEDDING_MODEL: bge-m3:567m
      API_PORT: 8000
    depends_on:
      - ollama-gpu
      - qdrant
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 15s
      timeout: 10s
      retries: 6
      start_period: 10s

volumes:
  ollama_data:
  qdrant_data: