spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:/app/auth.db}
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLiteDialect
      ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: health